Welcome to the module introducing `pandas` in AccFin Research.

`pandas` is the most useful Python library for data analysis in our research. In the second module, you will learn how to use `pandas` to handle data in tabular form. We will cover the fundamental operations needed to load data, explore it, clean it, and prepare it for further analysis. By the end, you’ll have the skills to manage real-world datasets and apply `pandas` to replicate a saminal paper.

**Learning Outcomes**

By completing this class, you will be able to:

- Create and explore *Series* and *DataFrames*, the two core data structures in `pandas`.

- Import and export datasets from common formats such as CSV and Stata.

- Inspect and summarize data using built-in functions.

- Select, filter, and slice data to focus on what matters.

- Clean and transform datasets by handling missing values, renaming columns, and changing data types.

- Perform basic data analysis with sorting, grouping, and simple aggregations.

- Integrate pandas workflows into larger Python projects.

In [2]:
import pandas as pd

### 1. pandas Series

In [3]:
#create a Series object from a Python List object
List = ['Tesla','2023','1 TESLA ROAD, AUSTIN, TX', 106_618]
series = pd.Series(List)
print(series)

0                       Tesla
1                        2023
2    1 TESLA ROAD, AUSTIN, TX
3                      106618
dtype: object

In [4]:
#Slicing a Series object
print(series[0])
print(series[3:])

Tesla
3    106618
dtype: object

In [5]:
# Create a Series object, dict1, from a dictionary object
dict1 = {"CompName":"Tesla", "fyear":2023, "Address": "1 TESLA ROAD, AUSTIN, TX", "at": 106_618}
series1 = pd.Series(dict1)
print(series1)

CompName                       Tesla
fyear                           2023
Address     1 TESLA ROAD, AUSTIN, TX
at                            106618
dtype: object

In [6]:
# Same as:
series2 = pd.Series(['Tesla',2023,'1 TESLA ROAD, AUSTIN, TX', 106_618], index=['CompName', 'fyear', 'Address', 'at'])
print(series2)

CompName                       Tesla
fyear                           2023
Address     1 TESLA ROAD, AUSTIN, TX
at                            106618
dtype: object

In [7]:
#Slicing a Series object by the Index
print(series1["fyear"])
print(series1["Address":])

2023
Address    1 TESLA ROAD, AUSTIN, TX
at                           106618
dtype: object

The difference between a `list` and a pandas Series object is that:

- The elements in a Series object can be indexed by a label.
- A Series object can directly apply comparison:

In [8]:
List = [1,2,3,4,5,6,7,8,9,10]
series = pd.Series(List)

print(series > 5)
print('However, List cannot be compared to a scalar value:')

try:
    print(List > 5) #This will throw an error
except Exception as e:
    print(f'Error: {e}')

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
9     True
dtype: bool
However, List cannot be compared to a scalar value:
Error: '>' not supported between instances of 'list' and 'int'

In [9]:
series[series > 5]

5     6
6     7
7     8
8     9
9    10
dtype: int64

In [10]:
series1 == series2

CompName    True
fyear       True
Address     True
at          True
dtype: bool

### 2. pandas DataFrame - Basic
The difference between a *Series* object and a *DataFrame* object is that a Series object has only one row, while a DataFrame object is a table with multiple rows.

#### 2.1. Load data

In [11]:
#Load data from a csv file
df = pd.read_csv('data/comp_sample.csv', parse_dates=['datadate'])

# pd.read_stata('comp_sample.dta'); 
# pd.read_excel('comp_sample.xlsx'); 
# pd.read_sas('comp_sample.sas7bdat', format = 'sas7bdat', encoding="utf-8")

# df.to_csv('comp_sample.csv', index=False)
# df.to_stata('comp_sample.dta', ignore_index=True)

#### 2.2. DataFrame Attributes

In [15]:
#get a list of columns using the `columns` attrniute
list(df.columns)[5]

'curcd'

In [16]:
df.dtypes

gvkey                int64
datadate    datetime64[ns]
fyear              float64
indfmt              object
conm                object
curcd               object
at                 float64
capx               float64
ceq                float64
csho               float64
ni                 float64
oancf              float64
sale               float64
xrd                float64
costat              object
prcc_f             float64
au                 float64
state               object
dtype: object

In [17]:
df.shape

(116059, 18)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116059 entries, 0 to 116058
Data columns (total 18 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   gvkey     116059 non-null  int64
 1   datadate  116059 non-null  datetime64[ns]
 2   fyear     115854 non-null  float64
 3   indfmt    116059 non-null  object
 4   conm      116059 non-null  object
 5   curcd     115854 non-null  object
 6   at        83273 non-null   float64
 7   capx      72817 non-null   float64
 8   ceq       83075 non-null   float64
 9   csho      103172 non-null  float64
 10  ni        73296 non-null   float64
 11  oancf     73040 non-null   float64
 12  sale      73303 non-null   float64
 13  xrd       34352 non-null   float64
 14  costat    116059 non-null  object
 15  prcc_f    107338 non-null  float64
 16  au        82967 non-null   float64
 17  state     104273 non-null  object
dtypes: datetime64[ns](1), float64(11), int64(1), object(5)
memory usage: 15.9+ MB

In [20]:
df['at'].dtype

dtype('float64')

In [22]:
# Rename variable
df.rename(columns={'conm': 'Company_Name'}, inplace= True)

#### 2.3. Accessing DataFrames

In [24]:
df.head(10)

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
0,1004,2015-05-31,2014.0,INDL,AAR CORP,USD,1515.000,46.300,845.100,35.423,10.200,-43.000,1594.300,NaN,A,29.54,6.0,IL
1,1004,2016-05-31,2015.0,INDL,AAR CORP,USD,1442.100,88.400,865.800,34.515,47.700,32.100,1662.600,NaN,A,24.41,6.0,IL
2,1004,2017-05-31,2016.0,INDL,AAR CORP,USD,1504.100,33.600,914.200,34.354,56.500,21.800,1767.600,NaN,A,34.94,6.0,IL
3,1004,2018-05-31,2017.0,INDL,AAR CORP,USD,1524.700,22.000,936.300,34.716,15.600,64.300,1748.300,NaN,A,44.69,6.0,IL
4,1004,2019-05-31,2018.0,INDL,AAR CORP,USD,1517.200,17.400,905.900,34.788,7.500,67.400,2051.800,NaN,A,30.09,6.0,IL
5,1004,2020-05-31,2019.0,INDL,AAR CORP,USD,2079.000,23.600,902.600,35.097,4.400,-36.100,2089.300,NaN,A,20.17,6.0,IL
6,1004,2021-05-31,2020.0,INDL,AAR CORP,USD,1539.700,11.300,974.400,35.375,35.800,105.200,1651.400,NaN,A,41.75,6.0,IL
7,1004,2022-05-31,2021.0,INDL,AAR CORP,USD,1573.900,17.300,1034.500,35.391,78.700,75.200,1817.100,NaN,A,48.22,6.0,IL
8,1004,2023-05-31,2022.0,INDL,AAR CORP,USD,1833.100,29.500,1099.100,34.916,90.200,23.300,1990.600,NaN,A,50.11,6.0,IL
9,1019,2015-12-31,2015.0,INDL,AFA PROTECTIVE SYSTEMS INC,USD,32.707,1.446,8.156,0.162,0.538,5.336,76.355,NaN,I,283.00,7.0,NY

In [25]:
df.tail()

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
116054,356289,2022-06-30,2022.0,INDL,SOLARBANK CORP,CAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,ON
116055,356289,2023-06-30,2023.0,INDL,SOLARBANK CORP,CAD,24.970,0.000,16.393,26.800,2.242,2.391,18.398,NaN,A,NaN,9.0,ON
116056,356687,2021-12-31,2021.0,INDL,ATHA ENERGY CORP,CAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,BC
116057,356687,2022-12-31,2022.0,INDL,ATHA ENERGY CORP,CAD,42.034,0.143,41.683,51.341,-1.030,-0.220,0.000,NaN,A,NaN,9.0,BC
116058,356687,2023-12-31,2023.0,INDL,ATHA ENERGY CORP,CAD,99.158,18.316,87.766,138.606,-13.976,-4.209,0.000,NaN,A,NaN,9.0,BC

In [27]:
df.sample(10)

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
98238,177376,2018-12-31,2018.0,INDL,DISCOVER FINANCIAL SVCS,USD,109553.000,254.000,10567.000,331.446,2742.000,5191.000,12848.000,NaN,A,58.98000,5.0,IL
7088,8702,2017-12-31,2017.0,FS,POWER CORP CANADA,CAD,445521.000,NaN,13650.000,NaN,NaN,NaN,NaN,NaN,A,32.37000,5.0,QC
16393,17161,2019-12-31,2019.0,INDL,MONTAUK METALS INC,USD,5.156,0.000,5.071,41.628,-1.365,-1.347,0.000,NaN,A,0.06296,9.0,ON
83509,145415,2015-08-31,2015.0,INDL,NUVEEN CA DIV ADV MUNI FD 3,USD,NaN,NaN,NaN,24.152,NaN,NaN,NaN,NaN,I,13.07000,NaN,IL
101711,179843,2017-12-31,2017.0,INDL,INTREPID POTASH INC,USD,511.054,13.505,402.553,127.647,-22.910,17.215,157.607,NaN,A,4.76000,6.0,CO
104129,183231,2016-12-31,2016.0,FS,SAGEN MI CANADA INC,CAD,6611.991,NaN,3648.580,NaN,NaN,NaN,NaN,NaN,I,33.66000,6.0,ON
67120,60990,2015-12-31,2015.0,FS,BNCCORP INC,USD,904.246,NaN,68.988,NaN,NaN,NaN,NaN,NaN,A,16.40000,6.0,ND
96580,176351,2018-06-30,2018.0,FS,ORITANI FINANCIAL CORP,USD,4167.039,NaN,559.346,NaN,NaN,NaN,NaN,NaN,I,16.20000,16.0,NJ
86940,157498,2021-12-31,2021.0,FS,PCB BANCORP,USD,2149.735,NaN,256.286,NaN,NaN,NaN,NaN,NaN,A,21.96000,16.0,CA
42509,30433,2023-12-31,2023.0,INDL,VANECK GREEN BOND ETF,USD,NaN,NaN,NaN,3.700,NaN,NaN,NaN,NaN,A,23.83010,NaN,NY

##### `.iloc` and `.loc`
**Key Differences**
|Feature|.loc|.iloc|
| --- | --- | --- |
|Selection|Label-based|Integer position-based|
|Slicing|Inclusive|Exclusive (Python's standard slicing)|
|Error Handling|Raises `KeyError` for invalid label|Raises `IndexError` for invalid position|

In [30]:
df.loc[:, ['gvkey', 'ni']]

         gvkey      ni
0         1004  10.200
1         1004  47.700
2         1004  56.500
3         1004  15.600
4         1004   7.500
...        ...     ...
116054  356289     NaN
116055  356289   2.242
116056  356687     NaN
116057  356687  -1.030
116058  356687 -13.976

[116059 rows x 2 columns]

##### Selecting columns

In [ ]:
df.loc[:, ['gvkey', 'ni']]

In [34]:
df[['gvkey', 'ni']]

         gvkey      ni
0         1004  10.200
1         1004  47.700
2         1004  56.500
3         1004  15.600
4         1004   7.500
...        ...     ...
116054  356289     NaN
116055  356289   2.242
116056  356687     NaN
116057  356687  -1.030
116058  356687 -13.976

[116059 rows x 2 columns]

##### Drop columns using `.drop()`

In [36]:
df1 = df.drop(columns=['ni', 'at'])

#### 2.4. Filtering
(Selecting Rows)

In [38]:
df[df['ni'] < 0]

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
20,1045,2020-12-31,2020.0,INDL,AMERICAN AIRLINES GROUP INC,USD,62008.000,1958.000,-6867.000,621.480,-8885.000,-6543.000,17337.000,NaN,A,15.77,6.0,TX
21,1045,2021-12-31,2021.0,INDL,AMERICAN AIRLINES GROUP INC,USD,66467.000,412.000,-7340.000,647.728,-1993.000,704.000,29882.000,NaN,A,17.96,6.0,TX
24,1050,2015-12-31,2015.0,INDL,CECO ENVIRONMENTAL CORP,USD,598.819,0.763,239.153,33.918,-5.602,12.637,367.422,NaN,A,7.68,11.0,TX
25,1050,2016-12-31,2016.0,INDL,CECO ENVIRONMENTAL CORP,USD,498.634,1.076,190.082,34.162,-38.218,69.599,417.011,NaN,A,13.95,11.0,TX
26,1050,2017-12-31,2017.0,INDL,CECO ENVIRONMENTAL CORP,USD,438.549,1.028,186.569,34.570,-3.029,6.570,345.051,NaN,A,5.13,11.0,TX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116032,351590,2020-12-31,2020.0,INDL,DAIMLER TRUCK HOLDING AG,USD,60256.041,959.487,9914.300,NaN,-172.370,5026.460,43409.566,1715.264,A,NaN,6.0,NaN
116042,353742,2022-11-30,2022.0,INDL,LI-FT PWR LTD,CAD,15.488,3.385,11.413,18.465,-0.738,-0.583,0.000,NaN,A,NaN,9.0,BC
116049,355398,2022-12-31,2022.0,INDL,SUPER HI INTERNATIONAL HOLDI,USD,576.112,60.471,239.806,61.933,-41.248,68.321,558.225,0.000,A,NaN,5.0,NaN
116057,356687,2022-12-31,2022.0,INDL,ATHA ENERGY CORP,CAD,42.034,0.143,41.683,51.341,-1.030,-0.220,0.000,NaN,A,NaN,9.0,BC
116058,356687,2023-12-31,2023.0,INDL,ATHA ENERGY CORP,CAD,99.158,18.316,87.766,138.606,-13.976,-4.209,0.000,NaN,A,NaN,9.0,BC

In [40]:
df[df['ni'] < 0][['gvkey', 'fyear']]

         gvkey   fyear
20        1045  2020.0
21        1045  2021.0
24        1050  2015.0
25        1050  2016.0
26        1050  2017.0
...        ...     ...
116032  351590  2020.0
116042  353742  2022.0
116049  355398  2022.0
116057  356687  2022.0
116058  356687  2023.0

[35447 rows x 2 columns]

In [43]:
df.loc[df['ni'] < 0, ['gvkey', 'fyear', 'ni']]

         gvkey   fyear        ni
20        1045  2020.0 -8885.000
21        1045  2021.0 -1993.000
24        1050  2015.0    -5.602
25        1050  2016.0   -38.218
26        1050  2017.0    -3.029
...        ...     ...       ...
116032  351590  2020.0  -172.370
116042  353742  2022.0    -0.738
116049  355398  2022.0   -41.248
116057  356687  2022.0    -1.030
116058  356687  2023.0   -13.976

[35447 rows x 3 columns]

In [45]:
df[df['gvkey'] == 1690]

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
673,1690,2015-09-30,2015.0,INDL,APPLE INC,USD,290479.0,11247.0,119355.0,5578.753,53394.0,81266.0,233715.0,8067.0,A,110.30,4.0,CA
674,1690,2016-09-30,2016.0,INDL,APPLE INC,USD,321686.0,12734.0,128249.0,5336.166,45687.0,65824.0,215091.0,10045.0,A,113.05,4.0,CA
675,1690,2017-09-30,2017.0,INDL,APPLE INC,USD,375319.0,12451.0,134047.0,5126.201,48351.0,63598.0,229234.0,11581.0,A,154.12,4.0,CA
676,1690,2018-09-30,2018.0,INDL,APPLE INC,USD,365725.0,13313.0,107147.0,4754.986,59531.0,77434.0,265359.0,14236.0,A,225.74,4.0,CA
677,1690,2019-09-30,2019.0,INDL,APPLE INC,USD,338516.0,10495.0,90488.0,4443.236,55256.0,69391.0,260174.0,16217.0,A,223.97,4.0,CA
678,1690,2020-09-30,2020.0,INDL,APPLE INC,USD,323888.0,7309.0,65339.0,16976.763,57411.0,80674.0,274515.0,18752.0,A,115.81,4.0,CA
679,1690,2021-09-30,2021.0,INDL,APPLE INC,USD,351002.0,11085.0,63090.0,16426.786,94680.0,104038.0,365817.0,21914.0,A,141.50,4.0,CA
680,1690,2022-09-30,2022.0,INDL,APPLE INC,USD,352755.0,10708.0,50672.0,15943.425,99803.0,122151.0,394328.0,26251.0,A,138.20,4.0,CA
681,1690,2023-09-30,2023.0,INDL,APPLE INC,USD,352583.0,10959.0,62146.0,15550.061,96995.0,110543.0,383285.0,29915.0,A,171.21,4.0,CA

In [46]:
df[df["Company_Name"].str.contains('APPLE')]

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
673,1690,2015-09-30,2015.0,INDL,APPLE INC,USD,290479.000,11247.000,119355.000,5578.753,53394.000,81266.000,233715.000,8067.000,A,110.3000,4.0,CA
674,1690,2016-09-30,2016.0,INDL,APPLE INC,USD,321686.000,12734.000,128249.000,5336.166,45687.000,65824.000,215091.000,10045.000,A,113.0500,4.0,CA
675,1690,2017-09-30,2017.0,INDL,APPLE INC,USD,375319.000,12451.000,134047.000,5126.201,48351.000,63598.000,229234.000,11581.000,A,154.1200,4.0,CA
676,1690,2018-09-30,2018.0,INDL,APPLE INC,USD,365725.000,13313.000,107147.000,4754.986,59531.000,77434.000,265359.000,14236.000,A,225.7400,4.0,CA
677,1690,2019-09-30,2019.0,INDL,APPLE INC,USD,338516.000,10495.000,90488.000,4443.236,55256.000,69391.000,260174.000,16217.000,A,223.9700,4.0,CA
678,1690,2020-09-30,2020.0,INDL,APPLE INC,USD,323888.000,7309.000,65339.000,16976.763,57411.000,80674.000,274515.000,18752.000,A,115.8100,4.0,CA
679,1690,2021-09-30,2021.0,INDL,APPLE INC,USD,351002.000,11085.000,63090.000,16426.786,94680.000,104038.000,365817.000,21914.000,A,141.5000,4.0,CA
680,1690,2022-09-30,2022.0,INDL,APPLE INC,USD,352755.000,10708.000,50672.000,15943.425,99803.000,122151.000,394328.000,26251.000,A,138.2000,4.0,CA
681,1690,2023-09-30,2023.0,INDL,APPLE INC,USD,352583.000,10959.000,62146.000,15550.061,96995.000,110543.000,383285.000,29915.000,A,171.2100,4.0,CA
5424,7117,2015-12-31,2015.0,INDL,MAUI LAND & PINEAPPLE CO,USD,46.599,0.000,-10.939,18.868,6.813,10.621,22.786,0.000,A,5.4600,9.0,HI
5425,7117,2015-12-31,2015.0,FS,MAUI LAND & PINEAPPLE CO,USD,46.599,NaN,-10.939,NaN,NaN,NaN,NaN,NaN,A,5.4600,9.0,HI
5426,7117,2016-12-31,2016.0,FS,MAUI LAND & PINEAPPLE CO,USD,38.883,NaN,17.742,NaN,NaN,NaN,NaN,NaN,A,7.2000,9.0,HI
5427,7117,2016-12-31,2016.0,INDL,MAUI LAND & PINEAPPLE CO,USD,38.883,0.268,17.742,18.958,21.814,33.877,47.364,0.000,A,7.2000,9.0,HI
5428,7117,2017-12-31,2017.0,FS,MAUI LAND & PINEAPPLE CO,USD,44.801,NaN,31.144,NaN,NaN,NaN,NaN,NaN,A,17.3000,9.0,HI
5429,7117,2017-12-31,2017.0,INDL,MAUI LAND & PINEAPPLE CO,USD,44.801,0.000,31.144,19.040,10.900,8.350,24.377,0.000,A,17.3000,9.0,HI
5430,7117,2018-12-31,2018.0,FS,MAUI LAND & PINEAPPLE CO,USD,48.100,NaN,30.919,NaN,NaN,NaN,NaN,NaN,A,9.9200,9.0,HI
5431,7117,2018-12-31,2018.0,INDL,MAUI LAND & PINEAPPLE CO,USD,48.100,0.311,30.919,19.126,0.498,0.882,11.037,0.000,A,9.9200,9.0,HI
5432,7117,2019-12-31,2019.0,FS,MAUI LAND & PINEAPPLE CO,USD,39.119,NaN,22.692,NaN,NaN,NaN,NaN,NaN,A,11.2500,9.0,HI
5433,7117,2019-12-31,2019.0,INDL,MAUI LAND & PINEAPPLE CO,USD,39.119,0.712,22.692,19.238,-10.366,1.772,10.045,0.000,A,11.2500,9.0,HI
5434,7117,2020-12-31,2020.0,INDL,MAUI LAND & PINEAPPLE CO,USD,38.470,0.081,20.067,19.312,-2.604,2.200,7.540,0.000,A,11.5300,9.0,HI
5435,7117,2020-12-31,2020.0,FS,MAUI LAND & PINEAPPLE CO,USD,38.470,NaN,20.067,NaN,NaN,NaN,NaN,NaN,A,11.5300,9.0,HI
5436,7117,2021-12-31,2021.0,FS,MAUI LAND & PINEAPPLE CO,USD,37.919,NaN,23.590,NaN,NaN,NaN,NaN,NaN,A,9.9600,9.0,HI
5437,7117,2021-12-31,2021.0,INDL,MAUI LAND & PINEAPPLE CO,USD,37.919,0.029,23.590,19.383,-3.420,1.387,12.443,0.000,A,9.9600,9.0,HI
5438,7117,2022-12-31,2022.0,INDL,MAUI LAND & PINEAPPLE CO,USD,42.406,0.000,33.772,19.477,1.787,6.263,20.960,0.000,A,9.4200,9.0,HI
5439,7117,2022-12-31,2022.0,FS,MAUI LAND & PINEAPPLE CO,USD,42.406,NaN,33.772,NaN,NaN,NaN,NaN,NaN,A,9.4200,9.0,HI
5440,7117,2023-12-31,2023.0,FS,MAUI LAND & PINEAPPLE CO,USD,42.223,NaN,34.704,NaN,NaN,NaN,NaN,NaN,A,15.8900,9.0,HI
5441,7117,2023-12-31,2023.0,INDL,MAUI LAND & PINEAPPLE CO,USD,42.223,0.618,34.704,19.615,-3.080,-1.371,10.915,0.000,A,15.8900,9.0,HI
30085,23977,2015-12-31,2015.0,INDL,APPLE HOSPITALITY REIT INC,USD,3722.775,0.000,2647.058,174.368,117.288,281.052,898.314,0.000,A,19.9700,4.0,VA
30086,23977,2016-12-31,2016.0,INDL,APPLE HOSPITALITY REIT INC,USD,4979.883,0.000,3517.064,222.939,144.652,332.034,1041.025,0.000,A,19.9800,4.0,VA
30087,23977,2017-12-31,2017.0,INDL,APPLE HOSPITALITY REIT INC,USD,4902.338,0.000,3571.085,229.962,182.492,384.741,1238.622,0.000,A,19.6100,4.0,VA
30088,23977,2018-12-31,2018.0,INDL,APPLE HOSPITALITY REIT INC,USD,4928.672,0.000,3409.010,223.997,206.086,404.812,1270.555,0.000,A,14.2600,4.0,VA
30089,23977,2019-12-31,2019.0,INDL,APPLE HOSPITALITY REIT INC,USD,4942.411,0.000,3291.013,223.863,171.917,381.674,1266.597,0.000,A,16.2500,4.0,VA
30090,23977,2020-12-31,2020.0,INDL,APPLE HOSPITALITY REIT INC,USD,4829.759,0.000,3029.347,223.212,-173.207,26.728,601.879,0.000,A,12.9100,4.0,VA
30091,23977,2020-12-31,2020.0,FS,APPLE HOSPITALITY REIT INC,USD,4829.759,NaN,3029.347,NaN,NaN,NaN,NaN,NaN,A,12.9100,4.0,VA
30092,23977,2021-12-31,2021.0,INDL,APPLE HOSPITALITY REIT INC,USD,4790.527,0.000,3147.321,228.256,18.828,217.562,933.869,0.000,A,16.1500,4.0,VA
30093,23977,2021-12-31,2021.0,FS,APPLE HOSPITALITY REIT INC,USD,4790.527,NaN,3147.321,NaN,NaN,NaN,NaN,NaN,A,16.1500,4.0,VA
30094,23977,2022-12-31,2022.0,INDL,APPLE HOSPITALITY REIT INC,USD,4772.714,0.000,3178.395,228.645,144.805,368.446,1238.417,0.000,A,15.7800,4.0,VA
30095,23977,2022-12-31,2022.0,FS,APPLE HOSPITALITY REIT INC,USD,4772.714,NaN,3178.395,NaN,NaN,NaN,NaN,NaN,A,15.7800,4.0,VA
30096,23977,2023-12-31,2023.0,INDL,APPLE HOSPITALITY REIT INC,USD,4937.298,0.000,3323.981,241.516,177.489,399.044,1343.800,0.000,A,16.6100,4.0,VA
30097,23977,2023-12-31,2023.0,FS,APPLE HOSPITALITY REIT INC,USD,4937.298,NaN,3323.981,NaN,NaN,NaN,NaN,NaN,A,16.6100,4.0,VA
33674,26080,2015-12-31,2015.0,INDL,PINEAPPLE INC,USD,3.922,0.330,-0.255,55.957,-1.188,-0.295,0.000,NaN,A,1.6800,9.0,CA
33675,26080,2016-12-31,2016.0,INDL,PINEAPPLE INC,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,2.5000,NaN,CA
33676,26080,2017-12-31,2017.0,INDL,PINEAPPLE INC,USD,0.769,0.057,-3.662,64.220,-1.100,-0.119,0.550,NaN,A,0.8500,NaN,CA
33677,26080,2018-12-31,2018.0,INDL,PINEAPPLE INC,USD,1.043,0.000,-4.298,65.863,-1.365,-0.268,0.010,NaN,A,0.7000,9.0,CA
33678,26080,2019-12-31,2019.0,INDL,PINEAPPLE INC,USD,12.009,0.000,0.721,76.891,-1.168,-0.252,0.015,NaN,A,0.4800,9.0,CA
33679,26080,2020-12-31,2020.0,INDL,PINEAPPLE INC,USD,9.504,0.000,6.730,88.461,-1.149,-0.544,0.000,NaN,A,0.0500,9.0,CA
33680,26080,2021-12-31,2021.0,INDL,PINEAPPLE INC,USD,9.397,0.000,6.332,91.164,-1.105,-0.053,0.000,NaN,A,0.0100,9.0,CA
33681,26080,2022-12-31,2022.0,INDL,PINEAPPLE INC,USD,0.002,0.000,-1.375,71.164,-7.856,-0.207,0.000,NaN,A,0.0087,9.0,CA
65589,41896,2021-08-31,2021.0,INDL,PINEAPPLE FINANCIAL INC,USD,7.581,0.062,6.918,6.307,-0.235,0.669,2.984,NaN,A,NaN,9.0,ON
65590,41896,2022-08-31,2022.0,INDL,PINEAPPLE FINANCIAL INC,USD,6.427,0.249,4.626,6.307,-2.810,-1.835,3.601,NaN,A,NaN,9.0,ON
65591,41896,2023-08-31,2023.0,INDL,PINEAPPLE FINANCIAL INC,USD,4.629,0.062,1.786,6.307,-2.809,-2.116,2.502,NaN,A,NaN,9.0,ON
84491,148876,2022-12-31,2022.0,INDL,APPLE ISPORT GROUP INC,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,2.2600,NaN,NaN
84492,148876,2023-12-31,2023.0,INDL,APPLE ISPORT GROUP INC,USD,0.069,0.000,-5.308,202.784,-3.678,-1.466,0.000,0.664,A,3.0300,9.0,NaN
101525,179700,2015-12-31,2015.0,INDL,DR PEPPER SNAPPLE GROUP INC,USD,8869.000,179.000,2183.000,187.842,764.000,991.000,6282.000,19.000,I,93.2000,5.0,TX
101526,179700,2016-12-31,2016.0,INDL,DR PEPPER SNAPPLE GROUP INC,USD,9791.000,180.000,2134.000,183.120,847.000,939.000,6440.000,20.000,I,90.6700,5.0,TX
101527,179700,2017-12-31,2017.0,INDL,DR PEPPER SNAPPLE GROUP INC,USD,10022.000,202.000,2451.000,179.743,1076.000,1038.000,6690.000,20.000,I,97.0600,5.0,TX

In [47]:
gvkeys = [1690, 12141, 35894]
df[df['gvkey'].isin(gvkeys)]

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
673,1690,2015-09-30,2015.0,INDL,APPLE INC,USD,290479.000,11247.000,119355.000,5578.753,53394.000,81266.000,233715.000,8067.000,A,110.30,4.0,CA
674,1690,2016-09-30,2016.0,INDL,APPLE INC,USD,321686.000,12734.000,128249.000,5336.166,45687.000,65824.000,215091.000,10045.000,A,113.05,4.0,CA
675,1690,2017-09-30,2017.0,INDL,APPLE INC,USD,375319.000,12451.000,134047.000,5126.201,48351.000,63598.000,229234.000,11581.000,A,154.12,4.0,CA
676,1690,2018-09-30,2018.0,INDL,APPLE INC,USD,365725.000,13313.000,107147.000,4754.986,59531.000,77434.000,265359.000,14236.000,A,225.74,4.0,CA
677,1690,2019-09-30,2019.0,INDL,APPLE INC,USD,338516.000,10495.000,90488.000,4443.236,55256.000,69391.000,260174.000,16217.000,A,223.97,4.0,CA
678,1690,2020-09-30,2020.0,INDL,APPLE INC,USD,323888.000,7309.000,65339.000,16976.763,57411.000,80674.000,274515.000,18752.000,A,115.81,4.0,CA
679,1690,2021-09-30,2021.0,INDL,APPLE INC,USD,351002.000,11085.000,63090.000,16426.786,94680.000,104038.000,365817.000,21914.000,A,141.50,4.0,CA
680,1690,2022-09-30,2022.0,INDL,APPLE INC,USD,352755.000,10708.000,50672.000,15943.425,99803.000,122151.000,394328.000,26251.000,A,138.20,4.0,CA
681,1690,2023-09-30,2023.0,INDL,APPLE INC,USD,352583.000,10959.000,62146.000,15550.061,96995.000,110543.000,383285.000,29915.000,A,171.21,4.0,CA
9998,12141,2015-06-30,2015.0,INDL,MICROSOFT CORP,USD,176223.000,5944.000,80083.000,8027.000,12193.000,29080.000,93580.000,12046.000,A,44.15,5.0,WA
9999,12141,2016-06-30,2016.0,INDL,MICROSOFT CORP,USD,193694.000,8343.000,71997.000,7808.000,16798.000,33325.000,85320.000,11988.000,A,51.17,5.0,WA
10000,12141,2017-06-30,2017.0,INDL,MICROSOFT CORP,USD,241086.000,8129.000,72394.000,7708.000,21204.000,39507.000,89950.000,13037.000,A,68.93,5.0,WA
10001,12141,2018-06-30,2018.0,INDL,MICROSOFT CORP,USD,258848.000,11632.000,82718.000,7677.000,16571.000,43884.000,110360.000,14726.000,A,98.61,5.0,WA
10002,12141,2019-06-30,2019.0,INDL,MICROSOFT CORP,USD,286556.000,13925.000,102330.000,7643.000,39240.000,52185.000,125843.000,16876.000,A,133.96,5.0,WA
10003,12141,2020-06-30,2020.0,INDL,MICROSOFT CORP,USD,301311.000,15441.000,118304.000,7571.000,44281.000,60675.000,143015.000,19269.000,A,203.51,5.0,WA
10004,12141,2021-06-30,2021.0,INDL,MICROSOFT CORP,USD,333779.000,20622.000,141988.000,7519.000,61271.000,76740.000,168088.000,20716.000,A,270.90,5.0,WA
10005,12141,2022-06-30,2022.0,INDL,MICROSOFT CORP,USD,364840.000,23886.000,166542.000,7464.000,72738.000,89035.000,198270.000,24512.000,A,256.83,5.0,WA
10006,12141,2023-06-30,2023.0,INDL,MICROSOFT CORP,USD,411976.000,28107.000,206223.000,7432.000,72361.000,87582.000,211915.000,27195.000,A,340.54,5.0,WA
54870,35894,2018-12-31,2018.0,INDL,DRAGANFLY INC,CAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,SK
54871,35894,2019-12-31,2019.0,INDL,DRAGANFLY INC,CAD,3.222,0.089,2.191,69.671,-11.095,-3.888,1.380,0.017,A,NaN,9.0,SK
54872,35894,2020-12-31,2020.0,INDL,DRAGANFLY INC,CAD,7.101,0.024,3.848,86.093,-8.016,-5.138,4.364,0.568,A,NaN,9.0,SK
54873,35894,2021-12-31,2021.0,INDL,DRAGANFLY INC,CAD,42.113,0.213,34.926,33.169,-16.203,-22.005,7.054,0.511,A,NaN,22.0,SK
54874,35894,2022-12-31,2022.0,INDL,DRAGANFLY INC,CAD,14.639,0.080,11.041,34.271,-27.654,-16.349,7.605,0.652,A,NaN,9.0,SK
54875,35894,2023-12-31,2023.0,INDL,DRAGANFLY INC,CAD,8.330,0.490,0.408,49.230,-23.612,-15.045,6.555,1.555,A,NaN,9.0,SK

In [53]:
condition1 = df['gvkey'].isin(gvkeys)
condition2 = df['ni'] > 50

df[(df['gvkey'].isin(gvkeys)) & (df['ni'] > 50)]

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
673,1690,2015-09-30,2015.0,INDL,APPLE INC,USD,290479.0,11247.0,119355.0,5578.753,53394.0,81266.0,233715.0,8067.0,A,110.30,4.0,CA
674,1690,2016-09-30,2016.0,INDL,APPLE INC,USD,321686.0,12734.0,128249.0,5336.166,45687.0,65824.0,215091.0,10045.0,A,113.05,4.0,CA
675,1690,2017-09-30,2017.0,INDL,APPLE INC,USD,375319.0,12451.0,134047.0,5126.201,48351.0,63598.0,229234.0,11581.0,A,154.12,4.0,CA
676,1690,2018-09-30,2018.0,INDL,APPLE INC,USD,365725.0,13313.0,107147.0,4754.986,59531.0,77434.0,265359.0,14236.0,A,225.74,4.0,CA
677,1690,2019-09-30,2019.0,INDL,APPLE INC,USD,338516.0,10495.0,90488.0,4443.236,55256.0,69391.0,260174.0,16217.0,A,223.97,4.0,CA
678,1690,2020-09-30,2020.0,INDL,APPLE INC,USD,323888.0,7309.0,65339.0,16976.763,57411.0,80674.0,274515.0,18752.0,A,115.81,4.0,CA
679,1690,2021-09-30,2021.0,INDL,APPLE INC,USD,351002.0,11085.0,63090.0,16426.786,94680.0,104038.0,365817.0,21914.0,A,141.50,4.0,CA
680,1690,2022-09-30,2022.0,INDL,APPLE INC,USD,352755.0,10708.0,50672.0,15943.425,99803.0,122151.0,394328.0,26251.0,A,138.20,4.0,CA
681,1690,2023-09-30,2023.0,INDL,APPLE INC,USD,352583.0,10959.0,62146.0,15550.061,96995.0,110543.0,383285.0,29915.0,A,171.21,4.0,CA
9998,12141,2015-06-30,2015.0,INDL,MICROSOFT CORP,USD,176223.0,5944.0,80083.0,8027.000,12193.0,29080.0,93580.0,12046.0,A,44.15,5.0,WA
9999,12141,2016-06-30,2016.0,INDL,MICROSOFT CORP,USD,193694.0,8343.0,71997.0,7808.000,16798.0,33325.0,85320.0,11988.0,A,51.17,5.0,WA
10000,12141,2017-06-30,2017.0,INDL,MICROSOFT CORP,USD,241086.0,8129.0,72394.0,7708.000,21204.0,39507.0,89950.0,13037.0,A,68.93,5.0,WA
10001,12141,2018-06-30,2018.0,INDL,MICROSOFT CORP,USD,258848.0,11632.0,82718.0,7677.000,16571.0,43884.0,110360.0,14726.0,A,98.61,5.0,WA
10002,12141,2019-06-30,2019.0,INDL,MICROSOFT CORP,USD,286556.0,13925.0,102330.0,7643.000,39240.0,52185.0,125843.0,16876.0,A,133.96,5.0,WA
10003,12141,2020-06-30,2020.0,INDL,MICROSOFT CORP,USD,301311.0,15441.0,118304.0,7571.000,44281.0,60675.0,143015.0,19269.0,A,203.51,5.0,WA
10004,12141,2021-06-30,2021.0,INDL,MICROSOFT CORP,USD,333779.0,20622.0,141988.0,7519.000,61271.0,76740.0,168088.0,20716.0,A,270.90,5.0,WA
10005,12141,2022-06-30,2022.0,INDL,MICROSOFT CORP,USD,364840.0,23886.0,166542.0,7464.000,72738.0,89035.0,198270.0,24512.0,A,256.83,5.0,WA
10006,12141,2023-06-30,2023.0,INDL,MICROSOFT CORP,USD,411976.0,28107.0,206223.0,7432.000,72361.0,87582.0,211915.0,27195.0,A,340.54,5.0,WA

In [54]:
df[
    ((df['ni'] < 0 ) | (df['ni']>5000)) &
    df['at'] > 100 &
    df['au'].isin([1,2,3,4])
   ][['gvkey', 'fyear']].head()

    gvkey   fyear
15   1045  2015.0
20   1045  2020.0
21   1045  2021.0
24   1050  2015.0
25   1050  2016.0

##### 2.4.1. query()

The `df.query()` method in pandas is a versatile tool for filtering DataFrame rows using string expressions. It supports a wide range of operations, allowing you to create complex queries that might be cumbersome with traditional boolean indexing. Here are some of the filtering capabilities you can achieve with `df.query()`:

- 1. **Basic Comparisons**

You can use comparison operators like `>`, `<`, `>=`, `<=`, `==`, and `!=` within the query string to filter data based on numeric or date-time conditions.

You can also check for membership `in` a list or array, which is useful for filtering categories or groups.

You can combine conditions using logical operators like `&`, `|`, and `~`.

In [ ]:
df.query('fyear == 2022')

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
8,1004,2023-05-31,2022.0,INDL,AAR CORP,USD,1833.100,29.500,1099.100,34.916,90.200,23.300,1990.600,NaN,A,50.110,6.0,IL
22,1045,2022-12-31,2022.0,INDL,AMERICAN AIRLINES GROUP INC,USD,64716.000,2906.000,-5799.000,650.642,127.000,2173.000,48971.000,NaN,A,12.720,6.0,TX
31,1050,2022-12-31,2022.0,INDL,CECO ENVIRONMENTAL CORP,USD,504.721,3.376,213.224,34.382,17.417,29.649,422.627,NaN,A,11.680,11.0,TX
47,1062,2022-11-30,2022.0,FS,ASA GOLD AND PRECIOUS METALS,USD,326.264,NaN,325.573,NaN,NaN,NaN,NaN,NaN,A,14.260,9.0,ME
48,1062,2022-11-30,2022.0,INDL,ASA GOLD AND PRECIOUS METALS,USD,326.264,NaN,325.573,19.290,-155.940,NaN,2.550,NaN,A,14.260,9.0,ME
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116045,353945,2022-12-31,2022.0,INDL,ACCELLERON INDUSTRIES AG,USD,981.551,34.425,283.784,93.751,122.801,133.388,780.538,51.087,A,20.693,6.0,NaN
116049,355398,2022-12-31,2022.0,INDL,SUPER HI INTERNATIONAL HOLDI,USD,576.112,60.471,239.806,61.933,-41.248,68.321,558.225,0.000,A,NaN,5.0,NaN
116051,356128,2022-12-31,2022.0,INDL,JOINT STOCK COMPANY KASPI KZ,USD,11072.847,128.568,1771.010,190.310,1264.809,2207.337,2746.982,131.463,A,66.000,5.0,NaN
116054,356289,2022-06-30,2022.0,INDL,SOLARBANK CORP,CAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,ON
116057,356687,2022-12-31,2022.0,INDL,ATHA ENERGY CORP,CAD,42.034,0.143,41.683,51.341,-1.030,-0.220,0.000,NaN,A,NaN,9.0,BC

In [56]:
df.query('fyear == 2022 | ((au in [1,2,3,4]) & (ni < 0))')

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
8,1004,2023-05-31,2022.0,INDL,AAR CORP,USD,1833.100,29.500,1099.100,34.916,90.200,23.300,1990.600,NaN,A,50.110,6.0,IL
22,1045,2022-12-31,2022.0,INDL,AMERICAN AIRLINES GROUP INC,USD,64716.000,2906.000,-5799.000,650.642,127.000,2173.000,48971.000,NaN,A,12.720,6.0,TX
31,1050,2022-12-31,2022.0,INDL,CECO ENVIRONMENTAL CORP,USD,504.721,3.376,213.224,34.382,17.417,29.649,422.627,NaN,A,11.680,11.0,TX
47,1062,2022-11-30,2022.0,FS,ASA GOLD AND PRECIOUS METALS,USD,326.264,NaN,325.573,NaN,NaN,NaN,NaN,NaN,A,14.260,9.0,ME
48,1062,2022-11-30,2022.0,INDL,ASA GOLD AND PRECIOUS METALS,USD,326.264,NaN,325.573,19.290,-155.940,NaN,2.550,NaN,A,14.260,9.0,ME
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116045,353945,2022-12-31,2022.0,INDL,ACCELLERON INDUSTRIES AG,USD,981.551,34.425,283.784,93.751,122.801,133.388,780.538,51.087,A,20.693,6.0,NaN
116049,355398,2022-12-31,2022.0,INDL,SUPER HI INTERNATIONAL HOLDI,USD,576.112,60.471,239.806,61.933,-41.248,68.321,558.225,0.000,A,NaN,5.0,NaN
116051,356128,2022-12-31,2022.0,INDL,JOINT STOCK COMPANY KASPI KZ,USD,11072.847,128.568,1771.010,190.310,1264.809,2207.337,2746.982,131.463,A,66.000,5.0,NaN
116054,356289,2022-06-30,2022.0,INDL,SOLARBANK CORP,CAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,ON
116057,356687,2022-12-31,2022.0,INDL,ATHA ENERGY CORP,CAD,42.034,0.143,41.683,51.341,-1.030,-0.220,0.000,NaN,A,NaN,9.0,BC

- 2. **String Operations**

`query()` supports string methods that can be used to filter rows based on string conditions. You must use the `str` accessor.

In [ ]:
df.query('Company_Name.str.startswith("A")')

,gvkey,datadate,fyear,indfmt,Company_Name,curcd,at,capx,ceq,csho,ni,oancf,sale,xrd,costat,prcc_f,au,state
673,1690,2015-09-30,2015.0,INDL,APPLE INC,USD,290479.0,11247.0,119355.0,5578.753,53394.0,81266.0,233715.0,8067.0,A,110.30,4.0,CA
674,1690,2016-09-30,2016.0,INDL,APPLE INC,USD,321686.0,12734.0,128249.0,5336.166,45687.0,65824.0,215091.0,10045.0,A,113.05,4.0,CA
675,1690,2017-09-30,2017.0,INDL,APPLE INC,USD,375319.0,12451.0,134047.0,5126.201,48351.0,63598.0,229234.0,11581.0,A,154.12,4.0,CA
676,1690,2018-09-30,2018.0,INDL,APPLE INC,USD,365725.0,13313.0,107147.0,4754.986,59531.0,77434.0,265359.0,14236.0,A,225.74,4.0,CA
677,1690,2019-09-30,2019.0,INDL,APPLE INC,USD,338516.0,10495.0,90488.0,4443.236,55256.0,69391.0,260174.0,16217.0,A,223.97,4.0,CA
678,1690,2020-09-30,2020.0,INDL,APPLE INC,USD,323888.0,7309.0,65339.0,16976.763,57411.0,80674.0,274515.0,18752.0,A,115.81,4.0,CA
679,1690,2021-09-30,2021.0,INDL,APPLE INC,USD,351002.0,11085.0,63090.0,16426.786,94680.0,104038.0,365817.0,21914.0,A,141.50,4.0,CA
680,1690,2022-09-30,2022.0,INDL,APPLE INC,USD,352755.0,10708.0,50672.0,15943.425,99803.0,122151.0,394328.0,26251.0,A,138.20,4.0,CA
681,1690,2023-09-30,2023.0,INDL,APPLE INC,USD,352583.0,10959.0,62146.0,15550.061,96995.0,110543.0,383285.0,29915.0,A,171.21,4.0,CA

- 3. **Null Checks**

You can check for null (or non-null) values using `isnull()` and `notnull()`.

- 4. **Variable Substitution**

You can include external variables in your query by prefixing them with an `@` symbol. This is useful for dynamic queries based on variable values.

- 5. **Complex Expressions**

You can use more complex expressions involving arithmetic operations, functions, and more.

**Note**: For some operations, especially those involving string methods or checking for null values, you need to specify the query engine as `python` because the default `numexpr` engine does not support all operations.

#### 2.5. Missing data

#### 2.6. Sort

#### 2.7. Duplicates

keep='first' (default): Marks duplicates as True except for the first occurrence.

keep='last': Marks duplicates as True except for the last occurrence.

keep=False: Marks all duplicates as True.

When removing duplicates, we have 3 options:
- `df.drop_duplicates(subset=['gvkey','fyear'], inplace=True)` keeps the **first** occurrence of unique combinations of `gvkey` and `fyear`.
- `df.drop_duplicates(subset=['gvkey','fyear'], keep='last', inplace=True)` keeps the **last** occurrence of unique combinations of `gvkey` and `fyear`.
- `df.drop_duplicates(subset=['gvkey','fyear'], keep=False, inplace=True)` keeps **none** of the duplicated combinations of `gvkey` and `fyear`.

#### 2.8. Generate Variables

##### 2.8.1. Working with Date

In [ ]:
# Turn a string or interger object into a datetime object
# If you have not included the `parse_dates = ['datadate']` argument in the `pd.read_csv()` function
df['datadate'] = pd.to_datetime(df['datadate'])

**Date Format**

`%Y`: Year with century as a decimal number (1779 or 2025).

`%y`: Year without century as a zero-padded decimal number (00-99).

`%m`: Month as a zero-padded decimal number (01-12).

`%B`: Full month name (January - December).

`%b`: Locale’s abbreviated month name (Jan - Dec).

`%d`: Day of the month as a zero-padded decimal number (01-31).

`%H`: Hour (24-hour clock) as a zero-padded decimal number (00-23).

`%I`: Hour (12-hour clock) as a zero-padded decimal number (01-12).

`%M`: Minute as a zero-padded decimal number (00-59).

`%S`: Second as a zero-padded decimal number (00-59).

`%p`: Locale’s equivalent of either AM or PM.

`%A`: Locale’s full weekday name.

`%a`: Locale’s abbreviated weekday name.

`%c`: Locale’s appropriate date and time representation.

##### 2.8.2. apply() function

### 3. Summary statistics

#### 3.1. Winsorization and Trucation

In [ ]:
from scipy.stats.mstats import winsorize

In [ ]:
# Alternatively, you can use the `winsorize` function from the `scipy.stats.mstats` module
from scipy.stats.mstats import winsorize
df['at_w1'] = winsorize(df['at'], limits=[.01,.01], inclusive=[False, False])

### 4. Groupby

#### 4.1. Aggregation
Aggregation is one of the most common uses of groupby(), where you compute a summary statistic (or statistics) about each group. 

For example, you can calculate the mean, median, sum, min, and max.

**Useful aggregate methods on Pandas**
- `count()`, `.sum()`	Total number of items
- `first()`, `last()`	First and last item
- `mean()`, `median()`	Mean and median
- `min()`, `max()`	Minimum and maximum
- `std()`, `var()`	Standard deviation and variance
- `prod()`	Product of all items
- `sum()`	Sum of all items

#### 4.2. Transformation
Transformation returns a DataFrame that is the same size as the input and is useful for operations such as filling NAs within groups with a value derived from each group.

#### **Homework**: Try to write the following function of winsorizing by group:

#### 4.3. Filtering
Sometimes you might want to filter the data based on the properties of the group.

For example, you might keep all the firms whose total asset is always larger than 100m.

#### 4.4 Summarizing
Using descrnie() on a groupby object to get a quick overview of the statistics for each group is also very common.

#### 4.5. Apply
The apply() method lets you apply a custom function to each group. This is useful for more complex operations that require a custom aggregation or transformation.

#### 4.6. Shift

This is not a good practice as it cannot tell if the previous observation is indeed for the previous year.

You should add:

### 5. Append and Merging

#### 5.1. Append using `pd.concat()`

#### 5.2. Merge using `pd.merge()`
Basic:

pd.merge(left_Dataframe, right_Dataframe, how='inner', on=[matching variables] {OR left_on= , right_on= })

In [ ]:
df1 = df.loc[1:75, ['gvkey','fyear','at','ceq']]
df2 = df.loc[51:150, ['gvkey','fyear','sale','ni']]

##### 5.2.1. One-to-one matching

##### 5.2.2. One-to-many matching

##### 5.2.3. Many-to-many merge

CCM: merge permno to Compustat data

In [ ]:
ccm = pd.read_csv('data/ccm.csv', parse_dates=['LINKDT','LINKENDDT'])

##### 5.2.4. Merge using SQLite (Optional)

In [ ]:
import sqlite3